/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.seleniumhq.selenium.selenium.java)
    api(libs.com.aventstack.extentreports)
    api(libs.io.github.bonigarcia.webdrivermanager)
    api(libs.io.cucumber.cucumber.java)
    testImplementation(libs.org.testng.testng)
    testImplementation(libs.io.cucumber.cucumber.testng)
}

group = "com.selenium"
version = "0.0.1-SNAPSHOT"
description = "testframework"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.register<JavaExec>("cucumber") {
    mainClass.set("io.cucumber.core.cli.Main")
    classpath = sourceSets["test"].runtimeClasspath
    args = listOf(
        "--glue", "stepdefinitions",
        "src/test/resources/features"
    )
}


tasks.named<Test>("test") {
    useTestNG() {
        include("**/TestRunner.class")
    }
}

